[package]
name = "playlist-maker"
version = "0.1.1"
authors = ["FilipeMCruz <filipeCruz@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "~2.33.0"
default-features = false
features = ["yaml", "suggestions", "color"]

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
walkdir = "2"
id3 = "0.5.1"
regex = "1.4.3"
num_cpus = "1.13.0"
